Final-Proyect-PETS/PROYECTO-FINAL-PETS

client/src/components/Register.jsx, client/src/redux/Actions/index.js, server/index.js, server/src/models/pets.js, server/src/models/users.js, server/src/routes/index.js
=> todo funca por ahora con errores

server/src/routes/index.js
rutas  de actualización de datos
=> rutasPacth

server/src/routes/index.js
get user by name y get pet by name terminado
=> Get user back ferri

server/src/models/pets.js
=> agregado de image pool

client/src/components/LandingPage.jsx, server/src/routes/index.js
=> filtros combinados back

client/src/components/SideBar/SideBar.jsx, client/src/redux/Actions/actionTypes.js, client/src/redux/Actions/index.js, client/src/redux/reducer.js, server/src/routes/index.js
LAUTI HACE LOS SORTS VOS NO ME JODAN MAS
=> los sorts son una mierda

client/src/components/PetRegister.jsx, client/src/redux/Actions/index.js, server/src/routes/index.js
Formulario de pets mejorado: agreega pool de imagenes, muestra alert de confirmacion antes de crear mascota, muestra alert de mascota creada correctamente.
=> Pets form update1

client/src/App.js, client/src/components/Details/PetDetail.jsx, client/src/components/Update/UpdateDataPet.jsx, client/src/components/Update/UpdateDataUsers.jsx, client/src/redux/Actions/actionTypes.js, client/src/redux/Actions/index.js, client/src/redux/reducer.js, server/src/routes/index.js
update pet y update user mejorados cris moreno
=> Update pet ferri

client/src/components/SideBar/SideBar.jsx
=> siguen los estilos

client/src/components/NavBar/NavBar.jsx, client/src/components/SideBar/SideBar.jsx
=> tomi color navbar y boton a crear perron

client/src/components/Register.jsx
cloudinary en form de register user andando
=> cloudinary en form de register user andando

client/src/components/Details/PetDetail.jsx, client/src/components/Details/UserDetail.jsx, client/src/redux/Actions/actionTypes.js, client/src/redux/Actions/index.js, client/src/redux/reducer.js
=> details_loading

client/src/components/Update/UpdateDataPet.jsx
=> adicciondeSelectUpdatePest

client/src/redux/Actions/index.js, server/src/routes/index.js
ya funciona relativamente bien el update
=> arreglodeactualizacion

client/src/components/Update/UpdateDataPet.jsx, client/src/components/Update/UpdateDataUsers.jsx, client/src/redux/Actions/index.js, server/src/routes/index.js
se controlo los formularos para desactivar el botón de actualizar si hay algún error y se arreglo el bug que al editar algún parámetro se creaba otro y no actualizaba el original
=> controfulariosyarreglobugs

client/src/components/Home/Card.jsx, client/src/components/Home/Cards.jsx, client/src/components/Home/UserCard.jsx, client/src/components/Update/UpdateDataPet.jsx, client/src/components/Update/UpdateDataUsers.jsx, server/src/routes/index.js
=> Placeholder form

server/src/utils/controllers/filters.js
=> Geolocalizacion

client/src/components/AdoptForm/AdoptForm.jsx, client/src/components/TradePet/TradePet.jsx, client/src/redux/Actions/index.js
se agrego un sweet alert y retorno al home después de enviar el mensaje de adopción
=> mejoraemail

client/src/components/Donaciones/Donation.jsx, client/src/redux/Actions/index.js, server/src/models/users.js, server/src/routes/index.js, server/src/routes/payment.js, server/src/routes/register.js, server/src/utils/controllers/register.js
Pasarela andando, falta corregir botones de pago y mostrar un mensaje de operacion exitosa.
=> Pasarela finit ferri

server/src/routes/patch.js
=> pequeño error arreglado

server/src/routes/patch.js
Reverts Final-Proyect-PETS/PROYECTO-FINAL-PETS#121 rompieron todo pelotdos
=> Revert "pequeño error arreglado"

client/src/components/AdoptForm/AdoptForm.jsx, server/src/models/users.js, server/src/routes/patch.js, server/src/utils/controllers/gets.js
Reverts Final-Proyect-PETS/PROYECTO-FINAL-PETS#120
=> Revert "Sabado"

client/src/components/Donaciones/Donation.jsx, client/src/redux/Actions/index.js, server/src/models/users.js, server/src/routes/index.js, server/src/routes/payment.js, server/src/routes/register.js, server/src/utils/controllers/register.js
Reverts Final-Proyect-PETS/PROYECTO-FINAL-PETS#119
=> Revert "Pasarela finit ferri"

client/src/components/Donaciones/Donation.jsx, client/src/redux/Actions/index.js, server/src/models/users.js, server/src/routes/index.js, server/src/routes/payment.js, server/src/routes/register.js, server/src/utils/controllers/register.js
=> Odiogithub

client/src/App.js, client/src/components/Donaciones/Donation.jsx, client/src/components/DonationCancelled.jsx, client/src/components/DonationPending.jsx, client/src/components/DonationSuccessful.jsx, server/src/routes/index.js
=> Averquesale

client/src/redux/Actions/index.js, server/src/routes/patch.js, server/src/routes/payment.js
se le agrego el ok a el sweet alert y se arreglo lo del email
=> arreglandodetalles

client/src/redux/Actions/index.js, client/src/redux/reducer.js, server/src/routes/patch.js
=> sweet adopt botton

client/src/components/Donations/Donation.jsx, server/src/routes/index.js, server/src/routes/payment.js
Terminé de modularizar MP asi Manu no me putea, limpié el codigo y le agregué la fecha de donacion y el dato de si el pago esta acreditado.
=> modularizado MP y mas

client/src/components/UserRegister.jsx
agregado campo para confirmar contraseña en el formulario de registro de usuario
=> cbugsito de confirmar contraseña

client/src/components/LandingPage.jsx, server/src/routes/gets.js, server/src/utils/controllers/login.js
=> dale aprobame

client/package-lock.json, client/package.json, client/src/components/Details/PetDetail.jsx
=> hice lo que pude

client/public/index.html, client/src/components/NavBar/NavBar.jsx, client/src/components/TradePet/Notifications.jsx, client/src/redux/Actions/index.js, client/src/redux/reducer.js
=> pushpushpush

client/src/components/Details/PetDetail.jsx, client/src/components/MissingDataRequired.js, client/src/components/Update/UpdateDataPet.jsx, client/src/components/Update/UpdateDataUsers.jsx
mapita en missing y bugs de mapita corregidos
=> mapita en missing y bugs de mapita corregidos
